/**
 * Data classification used everywhere in Solink.
 * Every number shown to a user should carry one of these labels.
 */
export type DataClass =
  | "source"       // REAL / SOURCE DATA: directly from a trusted source (manufacturer, weather API, hardware)
  | "calculated"   // CALCULATED: deterministic math on real inputs
  | "estimated"    // ESTIMATED: based on assumptions or estimation models
  | "ai"           // AI INTERPRETATION: generated by Claude from available data
  | "demo"         // DEMO DATA — NOT REAL
  | "user"         // USER-PROVIDED: entered by the user (an input, not a verified fact)
  | "unavailable"; // Not enough data / integration not connected

export const DATA_CLASS_LABEL: Record<DataClass, string> = {
  source: "Source data",
  calculated: "Calculated by Solink",
  estimated: "Estimate",
  ai: "AI interpretation",
  demo: "DEMO DATA — NOT REAL",
  user: "User-provided",
  unavailable: "Unavailable",
};

export const DATA_CLASS_DESCRIPTION: Record<DataClass, string> = {
  source: "Taken directly from a trusted source such as a manufacturer datasheet, the weather API, or monitoring hardware.",
  calculated: "Computed by Solink from real inputs using a transparent formula. Accurate only if the inputs are.",
  estimated: "Based on stated assumptions or an estimation model. Treat as indicative, not measured.",
  ai: "Generated by the AI Solar Agent from the data available to it. It can be wrong and should be checked.",
  demo: "Placeholder demonstration data. It does not describe any real product, system, or measurement.",
  user: "Entered by you. Solink has not verified it.",
  unavailable: "Solink does not have enough information or the required integration is not connected.",
};

/** A value with provenance. Use for anything displayed as a metric. */
export interface Classified<T = number> {
  value: T | null;
  cls: DataClass;
  /** Short source description, e.g. "Manufacturer datasheet", "WeatherAPI.com", "Solink calculator" */
  source?: string;
  /** Assumptions or notes that materially affect interpretation */
  notes?: string[];
  /** If unavailable, why (often a placeholder string) */
  reason?: string;
}

export function unavailable<T = number>(reason: string): Classified<T> {
  return { value: null, cls: "unavailable", reason };
}

export function classified<T>(value: T, cls: DataClass, source?: string, notes?: string[]): Classified<T> {
  return { value, cls, source, notes };
}
