/**
 * Layer 2 help: homeowner-friendly definitions for technical terms.
 * Rendered by <InfoTip term="..."/>.
 */
export interface GlossaryEntry { term: string; short: string; long?: string; }

export const GLOSSARY: Record<string, GlossaryEntry> = {
  kwh: { term: "kWh (kilowatt-hour)", short: "A unit of energy. One kWh runs a 1,000-watt appliance for one hour. Your electricity bill is measured in kWh." },
  kw: { term: "kW (kilowatt)", short: "A unit of power. How fast energy is produced or used at a moment. 1 kW = 1,000 watts." },
  kwp: { term: "kWp (kilowatt-peak)", short: "The rated size of a solar system under standard test conditions. Real output is usually lower and varies with weather." },
  efficiency: { term: "Panel efficiency", short: "The share of sunlight a panel turns into electricity. Higher efficiency means more power from the same roof area." },
  system_capacity: { term: "System capacity", short: "The total rated power of all panels combined, usually in kWp. A bigger system produces more energy but needs more roof space and budget." },
  payback_period: { term: "Payback period", short: "How many years until the money you save on electricity equals what you paid for the system. Depends heavily on the electricity tariff." },
  irradiance: { term: "Solar irradiance", short: "How much sunlight energy lands on a surface, often given as kWh per square metre per day. Kuwait receives a lot, but the exact figure must come from a real data source." },
  peak_sun_hours: { term: "Peak sun hours", short: "The equivalent number of hours per day at full sunlight strength. Used to estimate daily production from system size." },
  co2_reduction: { term: "CO₂ reduction", short: "The estimated greenhouse gas avoided because solar electricity replaces grid electricity. Depends on the grid's emission factor." },
  energy_production: { term: "Energy production", short: "The electricity your system generates over a period (day, month, year), measured in kWh." },
  degradation: { term: "Degradation", short: "Solar panels slowly produce a little less each year. Manufacturers state an expected rate in their performance warranty." },
  peak_power: { term: "Peak power (Pmax)", short: "The maximum power a panel can produce under standard test conditions, in watts (W)." },
  inverter: { term: "Inverter", short: "The device that converts the DC electricity from panels into the AC electricity your home uses. It also usually provides monitoring data." },
  battery: { term: "Battery storage", short: "Stores solar electricity for use at night or during outages. Optional; adds cost." },
  voc: { term: "Voc (open-circuit voltage)", short: "The panel's voltage when nothing is connected. Installers use it to design safe string sizes." },
  isc: { term: "Isc (short-circuit current)", short: "The panel's maximum current. Used for wiring and protection sizing." },
  vmp: { term: "Vmp (voltage at max power)", short: "The voltage at which the panel produces its rated power." },
  imp: { term: "Imp (current at max power)", short: "The current at which the panel produces its rated power." },
  temperature_coefficient: { term: "Temperature coefficient", short: "How much power a panel loses for every degree above 25 °C. Important in hot climates like Kuwait. A smaller loss is better." },
  performance_ratio: { term: "Performance ratio", short: "The share of theoretically possible production a real system delivers after losses from heat, dust, wiring and the inverter." },
  performance_warranty: { term: "Performance warranty", short: "The manufacturer's promise of how much of the original power the panel will still produce after a number of years." },
  product_warranty: { term: "Product warranty", short: "Covers defects in the panel itself (materials and workmanship) for a stated number of years." },
  // Roof planner (Solar Designer), written for a parent who has never bought a panel.
  roof_size: { term: "Roof size", short: "The length and width of the flat part of your roof, in metres. Pace it out or read it off your house plans. Solink draws the roof to this size; it cannot measure it from a photo." },
  obstacle: { term: "Things on the roof", short: "A water tank, an air-conditioning unit, a stairwell door or a satellite dish. Panels cannot go where these are, so telling Solink about them gives you a truthful count." },
  panel_count: { term: "Panels that fit", short: "How many panels of the chosen model fit on your roof at their real size, leaving space at the edges. Pure geometry; a real installer may fit a few more or fewer." },
  coverage: { term: "Roof used", short: "The share of your open roof that panels cover. Around half is common on a flat roof once you leave room to walk and clean." },
  rated_power: { term: "Panel power (W)", short: "How much power one panel makes in bright test conditions, in watts. A 585 W panel is a large, modern one. Multiply by the number of panels to get your system size." },
  auto_fill: { term: "Fill my roof", short: "Solink places as many panels as fit in neat rows, keeping a clear strip at the edges and avoiding anything you marked on the roof. You can drag any panel afterwards." },
  get_inspired: { term: "Ready layouts", short: "Three starting points: the most panels; rows with a walkway for cleaning; or panels plus a corner kept free for sitting out. Pick one, then change what you like." },
  setback: { term: "Space at the edges", short: "A clear strip along every roof edge, so someone can walk around the panels safely and clean them. Half a metre is the usual starting point." },
  walkway: { term: "Walkway", short: "A gap between rows of panels wide enough to walk and clean. In Kuwait's dust, being able to reach every panel matters." },
  modules: { term: "Walkways, planters and seating", short: "Blocks you can add to the drawing besides panels, at the size you type: a walkway, a planter box, a bench, a pergola. Select one and drag its corner to resize it. They are only shapes; Solink knows no prices or products for them. Panels cannot be resized, because a panel is a real product at its real size." },
  photo_trace: { term: "Photo of the roof", short: "You can put a photo of your roof under the drawing to see where things are, and draw boxes over the tank or the AC unit. The photo cannot measure anything; the size you typed stays the truth." },
  remaining_area: { term: "Space left", short: "Roof area not taken by panels, obstacles or the blocks you added. Useful for planning a sitting area or future panels." },
  panel_weight: { term: "Weight on the roof", short: "What the panels weigh in total, from the manufacturer's own figure. Mounting rails and ballast add more, and only a structural engineer can say what your roof can carry." },
  roof_load: { term: "What the roof can carry", short: "Every roof has a limit to the weight it can safely hold. It is written in the building's structural drawings or worked out by an engineer. Solink never guesses it." },
  yearly_production: { term: "Yearly production", short: "Roughly how much electricity the system would make in a year, in kWh, using Kuwait's sun hours and typical system losses. An estimate to size a system by, not a promise." },
  estimated_cost: { term: "Estimated cost", short: "Panel price times the number of panels, plus installation when a company has quoted one. Solink shows nothing until real prices exist." },
  // Site-wide sweep (2026-09-22): every technical label a parent may meet gets an ⓘ.
  production_trend: { term: "Production trend", short: "Whether your system is making more or less electricity than it did recently, in percent. A steady fall over weeks often means dust; a sudden drop points at a fault." },
  repeated_incidents: { term: "Repeated incidents", short: "How many problems were reported on your system in the last twelve months. Several of the same kind is a reason to ask an installer to look." },
  system_age: { term: "System age", short: "Years since the installation date recorded in your Solar Passport. Panels commonly last 25 years or more; inverters usually less." },
  maintenance_costs: { term: "Maintenance costs", short: "What cleaning, inspections and repairs cost. Solink only shows a cost when a company has actually entered it; it never estimates one." },
  detected_issue: { term: "Detected issue", short: "What Solink noticed in your data that started this case, for example production falling faster than the weather explains. A signal to check, not a diagnosis." },
  case_status: { term: "Case status", short: "Where a maintenance job is: new, being reviewed, scheduled, in progress, resolved or closed. Only steps that actually happened show a date." },
  cleaning_effect: { term: "Before and after", short: "Production in the days before a cleaning or repair compared with the days after. A rise suggests it helped; weather can move the number too." },
  cleaning_interval: { term: "Days since last cleaning", short: "How long since a cleaning was recorded. In Kuwait's dust, output often falls noticeably after a few weeks without one." },
  estimated_savings: { term: "Estimated savings", short: "The electricity you did not have to buy, valued at your tariff sector's price. It is an estimate: it depends on the tariff and on which figures Solink has." },
  production_by_year: { term: "Production by year", short: "Total electricity your system made in each calendar year, from the daily records Solink holds. Only complete years are fair to compare." },
  years_with_records: { term: "Years with records", short: "How many calendar years Solink has production data for. Trends need at least one full year to mean anything." },
  end_of_life: { term: "End of life", short: "When a panel or inverter should be replaced: it produces too little, has a safety defect, costs more to repair than to replace, or has failed after its warranty. An installer confirms." },
  ai_analysis: { term: "AI analysis", short: "A reading of your report or photo by Solink's AI. It can only see what you gave it, says so when that is not enough, and is never a professional diagnosis." },
  live_monitoring: { term: "Live monitoring", short: "Real-time readings from your inverter or a monitoring device. Solink shows them only once such hardware is connected; until then it says so plainly." },
  nearby_comparison: { term: "Nearby comparison", short: "How your system does against anonymous systems near you, to tell weather from a problem on your roof. Needs a privacy design first, so it is not available yet." },
  weather_production: { term: "Weather and production", short: "Your daily production shown next to the weather that day. Cloud, heat and dust all lower output; seeing them together stops a normal dip from looking like a fault." },
  quote_request: { term: "Quote request", short: "You send your saved design to installers and ask what they would charge. Nothing is bought or paid at this step; Solink handles no payments." },
  urgent_case: { term: "Urgent cases", short: "Open jobs marked high priority, usually because production dropped sharply or a safety issue was reported." },
  unassigned_case: { term: "Unassigned", short: "Open jobs that no technician has been given yet." },
  verification_status: { term: "Verification status", short: "Whether a Solink administrator has checked this information against the manufacturer's own documents. Unverified means nobody has yet; it does not mean wrong." },
  listing_status: { term: "Listing status", short: "Whether a product is shown in the marketplace (Listed), flagged because a newer datasheet exists (Outdated), or hidden (Archived)." },
  datasheet: { term: "Datasheet", short: "The manufacturer's official document with a product's technical figures. Solink's numbers are checked against it, so every product needs one." },
  data_class: { term: "Data class", short: "The little badge on every number saying what it is: source data from a document, calculated by Solink, an estimate, your own input, an AI reading, demo data, or unavailable." },
  assumptions: { term: "Assumptions", short: "Figures an estimate rests on, such as the electricity tariff or sun hours. Solink shows them next to the result so you can see what it rests on and change them." },
  monthly_consumption: { term: "Monthly electricity use", short: "How much electricity your home uses in a month, in kWh, from your bill. It sets how large a system makes sense." },
  location_use: { term: "Your location", short: "Used to place your roof on the map and, once connected, to fetch weather for your area. Companies you hire see only your governorate, never the address." },
  notifications_delivery: { term: "Delivery", short: "How Solink reaches you. Today notifications appear only inside Solink; email or SMS needs a provider that has not been chosen yet." },
  warranties: { term: "Warranties", short: "The product warranty covers defects in the equipment; the performance warranty promises how much power the panels will still make after a set number of years." },
  installation_record: { term: "Installation record", short: "Who installed the system, when, and exactly which equipment, frozen at that moment. A later change to a datasheet cannot rewrite it." },
  company_verification: { term: "Company verification", short: "Whether Solink's administrators have checked that a company or manufacturer is who it says it is. Only an administrator can set it." },
  tco: { term: "Total cost of ownership", short: "Everything a system costs over its life: purchase, installation, cleaning, maintenance, repairs and replacements." },
  energy_offset: { term: "Energy offset", short: "The share of your electricity use that solar covers. 100% means your system produces as much as you consume over the year." },
  pm25: { term: "PM2.5", short: "Very fine airborne particles (under 2.5 micrometres). An air-quality indicator. It hints at dusty conditions but is not a measurement of dust on your panels." },
  pm10: { term: "PM10", short: "Coarser airborne particles (under 10 micrometres), such as dust and sand. An environmental indicator, not a direct panel-soiling measurement." },
  soiling: { term: "Soiling", short: "Dust, sand or dirt on panels that blocks sunlight and reduces output. Cleaning restores it." },
  orientation: { term: "Roof orientation", short: "The compass direction your roof faces. In Kuwait, south-facing roofs generally receive the most sun over a year." },
  tilt: { term: "Tilt angle", short: "The angle of the panels from horizontal. Affects how much sunlight they capture across the seasons." },
  shading: { term: "Shading", short: "Anything that casts shadows on panels (buildings, tanks, trees) reduces production, sometimes disproportionately." },
  passport: { term: "Solar System Digital Passport", short: "Solink's permanent record of your installed system: equipment, installer, warranties and full maintenance history." },
  rls: { term: "Row Level Security", short: "A database rule that makes sure you can only see your own data." },
  string: { term: "String", short: "A group of panels wired together in series and connected to the inverter." },
  specific_yield: { term: "Specific yield", short: "Annual production per kWp installed (kWh/kWp). Useful for comparing systems of different sizes." },
};

export function glossary(key: string): GlossaryEntry | undefined {
  return GLOSSARY[key];
}
