-- ============================================================================
-- Solink — LONGi Hi-MO 7 LR8-66HGD 595~625M, 2026-09-23 (Session 9)
-- The 66-cell Hi-MO 7 format, requested by the owner as a CSV row
-- (LR8-66HGD-625M). Every bin the official datasheet lists, read from that
-- datasheet only; generated by gen_lr8.py (session scratchpad) with the same
-- checks as the part-2 import (Vmp × Imp ≈ Pmax, Vmp < Voc, Imp < Isc,
-- P ÷ area ≈ efficiency). Idempotent. No price: none found. No image yet.
-- See docs/DATA-CLEANING-LOG.md C-018.
-- ============================================================================

begin;

insert into data_sources (id, name, kind, url, notes) values
  ('da100000-0000-4000-8000-000000000012', 'LONGi official datasheet — Hi-MO 7 LR8-66HGD 595~625M bifacial dual glass (20240705 V03)', 'datasheet', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf', 'Text layer present. Source for every technical specification of the seven LONGi LR8-66HGD rows. Requested by the owner on 2026-09-23 (CSV row LR8-66HGD-625M); the whole series was imported from the same sheet.')
on conflict (id) do nothing;


-- LR8-66HGD-595M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-595M',
  'LONGi Hi-MO 7 LR8-66HGD-595M (595 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 595, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 22.0, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 47.78, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 15.8, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 39.91, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 14.91, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- LR8-66HGD-600M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-600M',
  'LONGi Hi-MO 7 LR8-66HGD-600M (600 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 600, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 22.2, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 47.98, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 15.85, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 40.11, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 14.96, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- LR8-66HGD-605M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-605M',
  'LONGi Hi-MO 7 LR8-66HGD-605M (605 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 605, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 22.4, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 48.18, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 15.9, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 40.31, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 15.01, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- LR8-66HGD-610M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-610M',
  'LONGi Hi-MO 7 LR8-66HGD-610M (610 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 610, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 22.6, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 48.38, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 15.95, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 40.51, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 15.06, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- LR8-66HGD-615M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-615M',
  'LONGi Hi-MO 7 LR8-66HGD-615M (615 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 615, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 22.8, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 48.58, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 16.0, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 40.71, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 15.11, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- LR8-66HGD-620M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-620M',
  'LONGi Hi-MO 7 LR8-66HGD-620M (620 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 620, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 23.0, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 48.78, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 16.05, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 40.91, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 15.16, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- LR8-66HGD-625M ------------------------------------------------------------
insert into solar_products (
  category, manufacturer_id, provider_id, model, name, description, series, images,
  price, currency, specs, source, is_demo, is_archived, is_outdated
)
select
  'solar_panel', m.id, null,
  'LR8-66HGD-625M',
  'LONGi Hi-MO 7 LR8-66HGD-625M (625 W bifacial)',
  'Bifacial dual-glass 132-half-cell module of LONGi''s Hi-MO 7 series, the 66-cell format beside the 72-cell LR7-72HGD. Specifications from the LONGi July 2024 datasheet (V03).',
  'Hi-MO 7',
  '{}'::text[],
  '{"value":null,"status":"unavailable"}'::jsonb,
  'KWD',
  jsonb_build_object(
    'rated_power_w', '{"value": 625, "unit": "W"}'::jsonb,
    'module_efficiency_pct', '{"value": 23.1, "unit": "%"}'::jsonb,
    'max_system_voltage_v', '{"value": 1500, "unit": "V"}'::jsonb,
    'voc_v', '{"value": 48.98, "unit": "V"}'::jsonb,
    'isc_a', '{"value": 16.1, "unit": "A"}'::jsonb,
    'vmp_v', '{"value": 41.11, "unit": "V"}'::jsonb,
    'imp_a', '{"value": 15.21, "unit": "A"}'::jsonb,
    'length_mm', '{"value": 2382, "unit": "mm"}'::jsonb,
    'width_mm', '{"value": 1134, "unit": "mm"}'::jsonb,
    'thickness_mm', '{"value": 30, "unit": "mm"}'::jsonb,
    'weight_kg', '{"value": 33.5, "unit": "kg"}'::jsonb,
    'cell_technology', '{"value": "Mono-crystalline half-cell, bifacial dual glass; the datasheet prints \"Advanced HPDC cell technology\""}'::jsonb,
    'number_of_cells', '{"value": 132, "unit": "cells (6×22)"}'::jsonb,
    'temperature_coefficient_pmax_pct_per_c', '{"value": -0.28, "unit": "%/°C"}'::jsonb,
    'operating_temperature_range_c', '{"value": "-40 to +85"}'::jsonb,
    'product_warranty_years', '{"value": 12, "unit": "years"}'::jsonb,
    'performance_warranty_years', '{"value": 30, "unit": "years"}'::jsonb,
    'performance_warranty_end_pct', '{"value": 87.4, "unit": "%"}'::jsonb,
    'expected_lifetime_years', '{"value": null, "status": "unavailable"}'::jsonb,
    'additional', jsonb_build_object(
      'temperature_coefficient_voc_pct_per_c', '{"value": -0.23, "unit": "%/°C"}'::jsonb,
      'temperature_coefficient_isc_pct_per_c', '{"value": 0.045, "unit": "%/°C"}'::jsonb,
      'noct_c', '{"value": 45, "unit": "°C ±2"}'::jsonb,
      'first_year_degradation_pct', '{"value": 1, "unit": "% (max, printed as <1 %)"}'::jsonb,
      'annual_degradation_year_2_30_pct', '{"value": 0.4, "unit": "%/year"}'::jsonb,
      'power_tolerance_pct', '{"value": "0 ~ +3"}'::jsonb,
      'bifaciality_pct', '{"value": 80, "unit": "% ±5"}'::jsonb,
      'max_series_fuse_a', '{"value": 35, "unit": "A"}'::jsonb,
      'glass', '{"value": "Dual glass, 2.0 + 2.0 mm heat-strengthened glass"}'::jsonb,
      'frame', '{"value": "Anodized aluminium alloy frame"}'::jsonb,
      'junction_box', '{"value": "IP68, three diodes"}'::jsonb,
      'front_load_pa', '{"value": 5400, "unit": "Pa"}'::jsonb,
      'rear_load_pa', '{"value": 2400, "unit": "Pa"}'::jsonb,
      'hail_test', '{"value": "25 mm hailstone at 23 m/s"}'::jsonb,
      'protection_class', '{"value": "Class II"}'::jsonb,
      'fire_rating', '{"value": "UL Type 29 / IEC Class C"}'::jsonb,
      'bifacial', '{"value": "Yes (dual glass, bifaciality 80 % ±5)"}'::jsonb
    )
  ),
  jsonb_build_object(
    'data_source', 'Manufacturer datasheet',
    'source_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'datasheet_url', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
    'manufacturer_doc_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_url', 'https://www.longi.com/en/products/modules/hi-mo-7/',
    'manufacturer_source_note', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03',
    'field_sources', jsonb_build_object(
      'rated_power_w', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'module_efficiency_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'max_system_voltage_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'voc_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'isc_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'vmp_v', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'imp_a', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'length_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'width_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'thickness_mm', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'weight_kg', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'cell_technology', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'number_of_cells', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'temperature_coefficient_pmax_pct_per_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'operating_temperature_range_c', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'product_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_years', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf',
      'performance_warranty_end_pct', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf'
    ),
    'date_added', '2026-09-23',
    'date_last_updated', '2026-09-23',
    'verification_status', 'unverified',
    'verification_note', 'Exact model and all technical specifications read from the official manufacturer datasheet (LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03) on 2026-09-23. No Kuwait retailer listing, price or availability was found for this model; price is unavailable, not estimated. The owner''s CSV gave 23.0 % efficiency for the 625 W bin; the datasheet prints 23.1 % and the datasheet value is stored. Not reviewed by a Solink admin.'
  ),
  false, false, false
from manufacturers m
where m.slug = 'longi'
on conflict (manufacturer_id, model) do update set
  name = excluded.name, description = excluded.description, series = excluded.series, images = excluded.images,
  price = excluded.price, currency = excluded.currency,
  specs = excluded.specs, source = excluded.source, provider_id = excluded.provider_id,
  is_demo = false, is_archived = false, is_outdated = false;

-- Provenance rows for the Hi-MO 7 rows (delete-then-insert keeps the file re-runnable)
delete from solar_product_sources s using solar_products p, manufacturers m
  where s.product_id = p.id and p.manufacturer_id = m.id and m.slug = 'longi' and p.model in ('LR8-66HGD-595M', 'LR8-66HGD-600M', 'LR8-66HGD-605M', 'LR8-66HGD-610M', 'LR8-66HGD-615M', 'LR8-66HGD-620M', 'LR8-66HGD-625M')
    and s.retrieved_at = date '2026-09-23' and s.source_type in ('official_manufacturer_datasheet', 'official_manufacturer_product_page');
insert into solar_product_sources (product_id, source_type, source_url, document_name, document_version, retrieved_at, fields, notes)
select p.id, 'official_manufacturer_datasheet', 'https://static.longi.com/L_Gi_LE_PM_T_PMD_059_F151_LR_8_66_HGD_595_625_M_V2_R_30_30_and_15_V3_1_EN_84644196a0.pdf', 'LONGi datasheet LR8-66HGD 595~625M, Hi-MO 7, 20240705 V03', '20240705 V03', date '2026-09-23', array['rated_power_w', 'module_efficiency_pct', 'max_system_voltage_v', 'voc_v', 'isc_a', 'vmp_v', 'imp_a', 'length_mm', 'width_mm', 'thickness_mm', 'weight_kg', 'cell_technology', 'number_of_cells', 'temperature_coefficient_pmax_pct_per_c', 'operating_temperature_range_c', 'product_warranty_years', 'performance_warranty_years', 'performance_warranty_end_pct'], 'Text layer present. Source for every technical specification of the seven LONGi LR8-66HGD rows. Requested by the owner on 2026-09-23 (CSV row LR8-66HGD-625M); the whole series was imported from the same sheet.'
from solar_products p join manufacturers m on m.id = p.manufacturer_id where m.slug = 'longi' and p.model in ('LR8-66HGD-595M', 'LR8-66HGD-600M', 'LR8-66HGD-605M', 'LR8-66HGD-610M', 'LR8-66HGD-615M', 'LR8-66HGD-620M', 'LR8-66HGD-625M');
insert into solar_product_sources (product_id, source_type, source_url, document_name, retrieved_at, fields, notes)
select p.id, 'official_manufacturer_product_page', 'https://www.longi.com/en/products/modules/hi-mo-7/', 'Manufacturer product page', date '2026-09-23', '{}'::text[],
  'The official page the datasheet is linked from. No product render was taken from it.'
from solar_products p join manufacturers m on m.id = p.manufacturer_id where m.slug = 'longi' and p.model in ('LR8-66HGD-595M', 'LR8-66HGD-600M', 'LR8-66HGD-605M', 'LR8-66HGD-610M', 'LR8-66HGD-615M', 'LR8-66HGD-620M', 'LR8-66HGD-625M');

commit;

-- Rollback (manual): delete from solar_products where model in ('LR8-66HGD-595M', 'LR8-66HGD-600M', 'LR8-66HGD-605M', 'LR8-66HGD-610M', 'LR8-66HGD-615M', 'LR8-66HGD-620M', 'LR8-66HGD-625M');
